spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-fhzsajjy.sql.tencentcdb.com:28352/user_center
    username: root
    password: Root123456789

# 关闭 Mybatis-Plus 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
knife4j:
  # 开启生产环境屏蔽
  production: true
