spring:
  profiles:
    active: dev
  application:
    name: user-center

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
      timeout: 1h

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: true # 逻辑已删除值(默认为 1)
      logic-not-delete-value: false # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.pikachu.usercenter.model.domain
  type-handlers-package: com.pikachu.usercenter.typehandler

